repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy --ignore-missing-imports
        language: system
        types: [ python ]
        pass_filenames: true
        files: bot/.+\.py$

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --config ruff.toml ./bot --fix
        language: system
        types: [ python ]
